require: rubocop-rspec
Documentation:
  Enabled: false
AllCops:
  RunRailsCops: true
  Include:
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'bin/**'
    - 'spec/teaspoon_env.rb'
    - 'node_modules/**/*'
    - 'config/initializers/devise.rb'
